/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.52 (Ubuntu)
 * Generated at: 2015-05-05 23:28:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.shoppingApp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class signup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<h2>Signup Page</h2>\r\n");
      out.write("<table>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td valign=\"top\">\r\n");
      out.write("            ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");

            
            Connection conn = null;
            PreparedStatement pstmt = null;
            ResultSet rs = null;
            PreparedStatement pstmt1 = null;
            ResultSet rs1 = null;
            
            try {
                // Registering Postgresql JDBC driver with the DriverManager
                Class.forName("org.postgresql.Driver");

                // Open a connection to the database using DriverManager
                conn = DriverManager.getConnection(
                    "jdbc:postgresql://localhost/cse135?" +
                    "user=postgres&password=postgres");
                
             
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");

                String action = request.getParameter("action");
                // Check if an insertion is requested
                if (action != null && action.equals("signup")) 
                {
				    if(request.getParameter("username") != "" && request.getParameter("usertype") != ""  && request.getParameter("age") != "" && request.getParameter("state") != "")
				    {
				    	
				    	String age = request.getParameter("age");
				    	int i = 0;
				    	
				    	boolean check = true;
				    	
				    	while(i < age.length()){ //checks for integer 
				    		char letter = age.charAt(i);
				    		int ascii = (int)letter;				    
				    		i++;
				    		if(ascii < 48 || ascii >= 58 ){ //invalid case - out of range
				    			check = false;
				    		}
				    		
				    	}
				    	
				    	
				    	if(check)
				    	{
						    // Begin transaction
		                    conn.setAutoCommit(false);
		
		                    // Create the prepared statement and use it to
		                    // INSERT user values INTO the users table.
		                    pstmt = conn
		                    .prepareStatement("INSERT INTO users (state, role, age, name) VALUES (?, ?, ?, ?)");
		
		                    pstmt.setString(4, request.getParameter("username"));
		                    pstmt.setString(2, request.getParameter("usertype"));
		                    pstmt.setInt(3, Integer.parseInt(request.getParameter("age")));
		                    pstmt.setString(1, request.getParameter("state"));
		  
		                    pstmt1 = conn.prepareStatement("select * from users where name = ?");
		                    pstmt1.setString(1, request.getParameter("name"));
		                    rs1 = pstmt1.executeQuery();
		                    
		                    if(!rs1.next()) //checks for name 
		                    {
		                    	int rowCount = pstmt.executeUpdate();
		                    	String username = (String) request.getParameter("username");
			                    application.setAttribute("username", username);
			                    String usertype = (String) request.getParameter("usertype");
			                    application.setAttribute("usertype", usertype);
			                    String redirectURL = "home.jsp";
			                    response.sendRedirect(redirectURL);
		                    }
		                    
		
		                    // Commit transaction
		                    conn.commit();
		                    conn.setAutoCommit(true);
		                    
		                    //Check 
		                    
		                    
				    	}
				    	else
				    	{
				    		 String redirectURL = "unsuccessful.html";
			                 response.sendRedirect(redirectURL);
				    	}
				    }	    
				    else
				    {
				    	 String redirectURL = "unsuccessful.html";
		                 response.sendRedirect(redirectURL);	
				    }
                }
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("           \r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");

                // Create the statement
                Statement statement = conn.createStatement();

                // Use the created statement to SELECT
                // the student attributes FROM the User table.
                rs = statement.executeQuery("SELECT * FROM users");
            
      out.write("\r\n");
      out.write("            \r\n");
      out.write("            <table border=\"1\">\r\n");
      out.write("            <form action=\"signup.jsp\" method=\"POST\">\r\n");
      out.write("\t            Username: <input type=\"text\" name=\"username\">\r\n");
      out.write("\t        \t<select name=\"usertype\">\r\n");
      out.write("\t        \t\t<option value=\"owner\" name=\"usertype\">Owner</option>\r\n");
      out.write("\t        \t\t<option value=\"customer\" name=\"usertype\">Customer</option>\r\n");
      out.write("\t        \t</select>\r\n");
      out.write("\t        \t<input type=\"hidden\" name=\"action\" value=\"signup\"/>\r\n");
      out.write("\t        \tAge: <input type=\"text\" name=\"age\">\r\n");
      out.write("\t        \t\r\n");
      out.write("\t        \t<select name=\"state\">\r\n");
      out.write("\t        \t\t<option value=\"\">- Please Select -</option>\r\n");
      out.write("\t        \t\t<option value=\"AL\">Alabama</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"AK\">Alaska</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"AZ\">Arizona</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"AR\">Arkansas</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CA\">California</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CO\">Colorado</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"CT\">Connecticut</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"DE\">Delaware</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"DC\">District Of Columbia</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"FL\">Florida</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"GA\">Georgia</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"HI\">Hawaii</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"ID\">Idaho</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"IL\">Illinois</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"IN\">Indiana</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"IA\">Iowa</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"KS\">Kansas</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"KY\">Kentucky</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"LA\">Louisiana</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"ME\">Maine</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MD\">Maryland</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MA\">Massachusetts</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MI\">Michigan</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MN\">Minnesota</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MS\">Mississippi</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MO\">Missouri</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"MT\">Montana</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NE\">Nebraska</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NV\">Nevada</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NH\">New Hampshire</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NJ\">New Jersey</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NM\">New Mexico</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NY\">New York</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"NC\">North Carolina</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"ND\">North Dakota</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"OH\">Ohio</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"OK\">Oklahoma</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"OR\">Oregon</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"PA\">Pennsylvania</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"RI\">Rhode Island</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"SC\">South Carolina</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"SD\">South Dakota</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"TN\">Tennessee</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"TX\">Texas</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"UT\">Utah</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"VT\">Vermont</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"VA\">Virginia</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"WA\">Washington</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"WV\">West Virginia</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"WI\">Wisconsin</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"WY\">Wyoming</option>\r\n");
      out.write("\t        \t</select>\r\n");
      out.write("\t        \t<td><input type=\"submit\" value=\"signup\"></td>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");

                // Iterate over the ResultSet
                while (rs.next()) {
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <tr>\r\n");
      out.write("                \r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      out.print(rs.getInt("id"));
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      out.print(rs.getString("state"));
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      out.print(rs.getString("role"));
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      out.print(rs.getInt("age"));
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                <td>\r\n");
      out.write("                    ");
      out.print(rs.getString("name"));
      out.write("\r\n");
      out.write("                </td>\r\n");
      out.write("\r\n");
      out.write("                <!--  \r\n");
      out.write("                <form action=\"attempt3/students.jsp\" method=\"POST\">\r\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"delete\"/>\r\n");
      out.write("                    <input type=\"hidden\" value=\"");
      out.print(rs.getInt("id"));
      out.write("\" name=\"id\"/>\r\n");
      out.write("                    Button\r\n");
      out.write("                <td><input type=\"submit\" value=\"Delete\"/></td>\r\n");
      out.write("                </form>-->\r\n");
      out.write("            </tr>\r\n");
      out.write("\r\n");
      out.write("            ");

                }
            
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            ");

                // Close the ResultSet
                rs.close();

                // Close the Statement
                statement.close();

                // Close the Connection
                conn.close();
            } catch (SQLException e) {
            	
                // Wrap the SQL exception in a runtime exception to propagate
                // it upwards
                
                //throw new RuntimeException(e);
                
            	String redirectURL = "unsuccessful.html";
                response.sendRedirect(redirectURL);
            }
            finally {
                // Release resources in a finally block in reverse-order of
                // their creation

                if (rs != null) {
                    try {
                        rs.close();
                    } catch (SQLException e) { } // Ignore
                    rs = null;
                }
                if (pstmt != null) {
                    try {
                        pstmt.close();
                    } catch (SQLException e) { } // Ignore
                    pstmt = null;
                }
                if (conn != null) {
                    try {
                        conn.close();
                    } catch (SQLException e) { 
                    	
                    	
                    	
                    } // Ignore
                    conn = null;
                }
            }
            
      out.write("\r\n");
      out.write("        </table>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
